### ISSUE TITLE
No support for __shfl_xor or __shfl_down for type double.

### ISSUE THREAD

**Issue by Jorghi12** [ROCm-Developer-Tools/HIP#434] opened 2018-05-07 17:16 UTC
I could not find a signature for the functions __shfl_xor or __shfl_down with type double. These should be added.

**Comment by aaronenyeshi** [comment] 2018-07-18 17:58
Hi @Jorghi12 double implementation was added in https://github.com/ROCm-Developer-Tools/HIP/pull/515

**Comment by mangupta** [comment] 2018-07-19 02:16
Marking as duplicate of #442. Closing it.

**Closed by mangupta** 2018-07-19 02:16 UTC
