### ISSUE TITLE
Pinned, mapped memory not bypassing GPU cache

### ISSUE THREAD

**Issue by founta** [ROCm-Developer-Tools/HIP#618] opened 2018-08-03 19:14 UTC
Hi there,
I was working with zero-copy memory in CUDA and wanted to port it all to HIP. I was having problems with reading zero-copy memory from within the kernel on AMD hardware that I had not encountered while using CUDA with NVIDIA hardware; it appeared that a zero-copy variable I was using as a condition for a while loop was not being updated when changed host-side. To resolve this, I found I either had to atomicAdd the variable with 0 to retrieve it, call __threadfence_system at the bottom of the loop, or put an 'asm volatile ("buffer_wbinvl1_vol")' at the bottom of that while loop.

As per the post by kayccc in the following link, in CUDA, "both CPU and GPU caches are bypassed for zero-copy memory"
https://devtalk.nvidia.com/default/topic/932957/zero-copy-and-managedmemory-%20on-jetson/?offset=2

I assumed that this would be the same with HIP, but it appears that the GPU cache is not bypassed when using HIP with an AMD GPU; the example below functioned when I manually invalidated and wrote back the L1 cache with buffer_wbinvl1_vol but never ran to completion if I didn't.

Here's a simple example that demonstrates the problem. It functions using either HIP with NVCC or HIP with HCC, but fails (spins forever on the stream synchronize) if the conditional 'asm volatile ("buffer_wbinvl1_vol")' call is removed from the kernel : 

```c++

//test_kernel.cpp
#include "hip/hip_runtime.h"

//increment some counters until we tell it to stop
extern "C" __global__ void
loopy(hipLaunchParm lp, int *persist, int *ctr)
{
  size_t idx = hipThreadIdx_x;
  ctr[idx] = 0;
  while (persist[0])
  {
    ctr[idx]++;
    #ifdef __HIP_PLATFORM_HCC__
    asm volatile ("buffer_wbinvl1_vol");
    #endif
  } //end while persist
} //end loopy
```

```c++

//test.cpp
/* amd compile : 
HCC_HOME=/opt/rocm/hcc /opt/rocm/hip/bin/hipcc test.cpp -o test_zero_copy -std=c++11  -L /opt/rocm/libhsakmt/lib -Wl,-rpath,/opt/rocm/libhsakmt/lib -L /opt/rocm/hsa/lib -Wl,-rpath, /opt/rocm/hsa/lib -L /opt/rocm/lib -Wl,-rpath /opt/rocm/lib -L /opt/rocm/hip/lib -Wl,-rpath /opt/rocm/hip/lib -L /opt/rocm/hcc/lib -Wl,-rpath, /opt/rocm/hcc/lib  -lhc_am -lhip_hcc -lhsakmt -lhsa-runtime64


nvcc compile :
CUDA_PATH=/usr/local/cuda-9.2 HCC_HOME=/opt/rocm/hcc /opt/rocm/hip/bin/hipcc -ccbin=gcc-6.2 test.cpp -o test_zero_copy -lstdc++ -Xcompiler -std=c++11 -std=c++11 -L/usr/local/cuda-9.2/lib64 -Xlinker -rpath,/usr/local/cuda-9.2/lib64 -L/usr/lib64 -Xlinker -rpath,/usr/lib64 -lcudart -lcuda

run :
./test_zero_copy
*/
#include <cstdio>  //fprintf
#include <iostream> //cerr
#include <unistd.h> //usleep

#include "hip/hip_runtime_api.h"

#define HIPCC "/opt/rocm/hip/bin/hipcc"

#define HCC_HOME "/opt/rocm/hcc"

#define CUDA_PATH "/usr/local/cuda-9.2"
#define CUDA_CC "gcc-6.2"

#define KERNEL_NAME "test_kernel"

#define CHECK(cmd)                                                             \
do {                                                                           \
  hipError_t error = (cmd);                                                    \
  if (error != hipSuccess)                                                     \
  {                                                                            \
    std::cerr << "Encountered HIP error (" << error << ") at line "            \
              << __LINE__ << " in file " << __FILE__ << "\n";                  \
    exit(-1);                                                                  \
  }                                                                            \
} while (0)

int main()
{
  //how many counters to run. defines number of GPU threads
  const size_t nr_counts = 5;

  //get two pairs of "zero-copy" int pointers
  int *h_persist, *d_persist;
  CHECK(hipHostMalloc((void**) &h_persist, sizeof(int), hipHostMallocMapped));
  CHECK(hipHostGetDevicePointer( (void**) &d_persist, (void*) h_persist, 0 ));

  int *h_count, *d_count;
  CHECK(hipHostMalloc((void**) &h_count, sizeof(int)*nr_counts, hipHostMallocMapped));
  CHECK(hipHostGetDevicePointer( (void**) &d_count, (void*) h_count, 0 ));

  //initialize persist to 1
  h_persist[0] = true;

  //create stream and compile kernel
  hipStream_t *stream = new hipStream_t;
  CHECK(::hipStreamCreate(stream));

  fprintf(stderr, "compiling kernel\n");
  #ifdef __HIP_PLATFORM_NVCC__
  system(" CUDA_PATH=" CUDA_PATH " HCC_HOME=" HCC_HOME " " HIPCC
         "  --genco -Xcompiler -std=c++11 -std=c++11 -ccbin=" CUDA_CC 
         " " KERNEL_NAME ".cpp -o " KERNEL_NAME ".co\n");
  #else  //HCC
  system("  HCC_HOME=" HCC_HOME " " HIPCC
         " --genco " KERNEL_NAME ".cpp -o " KERNEL_NAME ".co\n");
  #endif
  fprintf(stderr, "compiled kernel to binary\n");


  //load the module
  hipModule_t *module = new hipModule_t;
  fprintf(stderr, "loading in a module...\n");
  #ifdef __HIP_PLATFORM_HCC__
  CHECK(::hipModuleLoad(module, KERNEL_NAME ".co.adipose"));
  #else
  CHECK(::hipModuleLoad(module, KERNEL_NAME ".co"));
  #endif
  fprintf(stderr, "module loaded!\n");

  //set up kernel argument buffer
  
  //leave one extra word of cleared space in the beginning
  size_t size = sizeof(void*) * 3;
  void **args = (void**)calloc(1,size);
  args[1] = (void*)d_persist;
  args[2] = (void*)d_count;

  void *config[] =
  {
      HIP_LAUNCH_PARAM_BUFFER_POINTER, args,
      HIP_LAUNCH_PARAM_BUFFER_SIZE, &size,
      HIP_LAUNCH_PARAM_END
  };

  //launch the kernel
  hipFunction_t function;
  CHECK(::hipModuleGetFunction(&function, *module, "loopy"));
  CHECK(::hipModuleLaunchKernel(function,
      /*grid dim x,y,z*/        1, 1, 1,
      /*block dim x,y,z*/       nr_counts, 1, 1,
      /*dynamic shared mem*/    0,
      /*stream*/                *stream,
      /*always NULL*/           NULL,
      /*kernel args*/           (void**)&config) );

  //wait a short bit
  usleep(100000);

  //tell the kernel to stop and then synchronize
  h_persist[0] = false;

  fprintf(stderr, "synchronizing stream...\n");
  CHECK(::hipStreamSynchronize(*stream));
  fprintf(stderr, "synchronized!\n");
  
  fprintf(stderr, "counts :\n");
  for (size_t i = 0; i < 5; i++)
    fprintf(stderr, "%d : %d\n", i, h_count[i]);

  CHECK(::hipStreamDestroy(*stream));
  CHECK(::hipHostFree((void*) h_persist));
  CHECK(::hipHostFree((void*) h_count));
  CHECK(::hipModuleUnload(*module));

  free(args);
  delete stream;
  delete module;
}
```

The compile lines I've used are at the top of test.cpp. To get it to run, the #defines at the top of test.cpp will probably have to be changed, too.

Is this a problem or am I doing something wrong?

**Comment by gargrahul** [comment] 2018-08-08 05:04
@founta Pinned memory allocated using hipHostMalloc is not volatile. Since it is being accessed from both CPU and GPU , for coherency threadfence_system or atomics should be used.

**Comment by gargrahul** [comment] 2019-04-18 20:30
Closing this issue since it is an expected behavior.

**Closed by gargrahul** 2019-04-18 20:30 UTC
