### ISSUE TITLE
Installation of `*.cmake` files possibly wrong?

### ISSUE THREAD

**Issue by dipietrantonio** [ROCm-Developer-Tools/HIP#2787] opened 2022-07-06 17:02 UTC
Hi all,
I am installing ROCm on a custom location, let's say $INSTALL_DIR. When trying to compile rocSolver, i get the following error:

```
CMake Error at $INSTALL_DIR/hip/lib/cmake/hip/hip-config.cmake:199 (include):
  include could not find requested file:

    $INSTALL_DIR/hip/lib/cmake/hip/hip-targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:146 (find_package)
```
In fact, that file is located under `$INSTALL_DIR/lib/cmake/hip`.

My installation looks like this:
```
$ ls $INSTALL_DIR/hip/lib/cmake/hip/
hip-config.cmake  hip-config-version.cmake
$ ls $INSTALL_DIR/lib/cmake/hip
FindHIP  FindHIP.cmake  hip-config.cmake  hip-config-version.cmake  hip-targets.cmake  hip-targets-release.cmake
```
Is there a problem with the installation process?

**Comment by acxz** [comment] 2023-05-04 16:14
This should be closed as a dup of https://github.com/ROCm-Developer-Tools/HIP/issues/3145 and the newer issue has more discussion.

**Comment by milthorpe** [comment] 2023-11-27 01:01
I don't think this is a duplicate of #3145; the name of the missing file in that issue (`FindHIP.cmake`) is different to the file in this issue (`hip-targets.cmake`). I get the same error reported by @dipietrantonio using a [Spack build of hip@5.2.3+cuda](https://github.com/spack/spack/blob/v0.21.0/var/spack/repos/builtin/packages/hip/package.py)

**Comment by ppanchad-amd** [comment] 2024-04-09 14:46
@milthorpe Apologies for the lack of response. Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831) to see if issue still exists? Thanks!

**Comment by ppanchad-amd** [comment] 2024-06-28 17:58
@dipietrantonio @milthorpe Closing ticket. Please re-open if you still see the issue with the latest ROCm 6.1.2. Thanks!

**Closed as not planned by ppanchad-amd** 2024-06-28 17:58 UTC
