### ISSUE TITLE
Unit_hipDeviceSynchronize_Functional depends on timing and fails due to a simple compiler optimization

### ISSUE THREAD

**Issue by pvelesko** [ROCm-Developer-Tools/HIP#2982] opened 2022-10-11 12:32 UTC
More info:

https://github.com/CHIP-SPV/chip-spv/issues/186

**Comment by abhimeda** [comment] 2024-02-07 18:41
@pvelesko  Hi, were you able to resolve this issue on the latest HIP? If so can we close this ticket?

**Comment by pvelesko** [comment] 2024-02-20 04:26
@abhimeda no. https://github.com/ROCm/hip-tests/blob/569b088eb8a36d0ad060f48d1f3271a09e28674b/catch/unit/device/hipDeviceSynchronize.cc#L121 

There is 0 change since this issue was reported.

**Comment by ppanchad-amd** [comment] 2024-04-10 14:23
@pvelesko Internal ticket has been created to resolve this issue. Thanks!

**Comment by sohaibnd** [comment] 2024-10-30 19:41
Hi @pvelesko, sorry for the delay. Can you provide the full steps to reproduce this issue? When trying to run the Unit_hipDeviceSynchronize_Functional test without a GPU, I get the following error: "no ROCm-capable device is detected".

Also, note that there was a change to this test after the issue was reported: https://github.com/ROCm/hip-tests/pull/316

**Comment by sohaibnd** [comment] 2024-11-08 21:00
@pvelesko I'm closing this ticket due to inactivity. If the problem in the test is still present, please re-open this issue and provide steps to reproduce the failure.

**Closed as completed by sohaibnd** 2024-11-08 21:00 UTC
Labels: Under Investigation
