### ISSUE TITLE
unknown type name 'hipFunction_attribute' (roc-3.0.0 tag)

### ISSUE THREAD

**Issue by nikAizuddin** [ROCm-Developer-Tools/HIP#1874] opened 2020-02-16 03:32 UTC
When compiling [hipSYCL v0.8.0](https://github.com/illuhad/hipSYCL/tree/v0.8.0), i got the following error:
```
/opt/rocm/include/hip/hcc_detail/hip_prof_str.h:595:7: error: unknown type name 'hipFunction_attribute'; did you mean 'hipFuncAttributes'?
```

I need to patch `/opt/rocm/include/hip/hcc_detail/hip_prof_str.h` to make the compilation works:
```diff
@@ -592,7 +592,7 @@
     } hipMemPtrGetInfo;
     struct {
       int* value;
-      hipFunction_attribute attrib;
+      hipFuncAttributes attrib;
       hipFunction_t hfunc;
     } hipFuncGetAttribute;
     struct {
```

I want to send Pull Request but I'm not sure why `include/hip/hcc_detail/hip_prof_str.h` is included in `.gitignore`: https://github.com/ROCm-Developer-Tools/HIP/blob/36529b168022a644685a194cfd5e402948c98e3c/.gitignore#L16

**Comment by SarbojitAMD** [comment] 2020-02-17 13:52
hip_prof_str.h is a generated file hence it is marked as ignored files in git. There is a py file which generates this file. If you think any fix is needed you need to make change in the python file.

Regarding the change you have proposed I think there are two functions hipFuncGetAttribute and hipFuncGetAttributes ( Notice the extra 's' in second function) when first takes hipFunction_attribute as argument and second takes hipFuncAttributes as argument. None of these functions has got changed recently hence I am not sure why are you seeing compilation error with rocm3.0.

**Comment by nikAizuddin** [comment] 2020-02-17 15:57
@SarbojitAMD Also I think my patch doesn't make sense but I don't know why it works:
> ```diff
> @@ -592,7 +592,7 @@
>      } hipMemPtrGetInfo;
>      struct {
>        int* value;
> -      hipFunction_attribute attrib;
> +      hipFuncAttributes attrib;
>        hipFunction_t hfunc;
>      } hipFuncGetAttribute;
>      struct {
> ```

> None of these functions has got changed recently hence I am not sure why are you seeing compilation error with rocm3.0.

I see, probably I did some mistakes then. I'm going to rebuild ROCm and I'll update here.

**Comment by SarbojitAMD** [comment] 2020-02-17 17:16
closing it as 'not a bug' feel free to open a new ticket in case you need any more clarification.

**Closed by SarbojitAMD** 2020-02-17 17:16 UTC
Labels: type:not a bug

**Comment by nikAizuddin** [comment] 2020-02-18 14:19
@SarbojitAMD Alright. Btw I can confirm this not a bug. There are conflicts with hipSYCL's HIP submodule so do not pull that submodule. Here what I did to prevent the conflict when building hipSYCL.

Get hipSYCL source and pull only hipCPU submodule:
```bash
$ cd ~/projects
$ git clone -b v0.8.0 https://github.com/illuhad/hipSYCL.git
$ git submodule init contrib/hipCPU
$ git submodule update contrib/hipCPU
$ cd hipSYCL
```

Patch [CMakeLists.txt](https://github.com/illuhad/hipSYCL/blob/v0.8.0/CMakeLists.txt):
```diff
@@ -168,7 +168,6 @@ file(WRITE ${SYCLCC_CONFIG_FILE_PATH} ${SYCLCC_CONFIG_FILE})
 
 install(DIRECTORY include/CL DESTINATION include/ FILES_MATCHING PATTERN "*.hpp")
 install(DIRECTORY contrib/hipCPU/include/hipCPU DESTINATION include/hipSYCL/)
-install(DIRECTORY contrib/HIP/include/ DESTINATION include/hipSYCL/)
 
 install(PROGRAMS bin/syclcc DESTINATION bin)
 install(PROGRAMS bin/syclcc-clang DESTINATION bin)
```

Build, compile, and install:
```bash
$ mkdir build
$ cd build
$ export HIPSYCL_CUDA_PATH=""
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/rocm/hipsycl -DCLANG_EXECUTABLE_PATH=/opt/rocm/llvm/bin/clang -DWITH_ROCM_BACKEND=ON ..
$ make -j 16
$ sudo make -j 16 install
$ echo "/opt/rocm/hipsycl/lib" | sudo tee /etc/ld.so.conf.d/hipsycl.conf
$ sudo ldconfig
```

Add the following lines into `/etc/profile.d/rocm.sh`:
```
export HIPSYCL_CUDA_PATH=""
export HIPSYCL_GPU_ARCH="gfx900"
export HIPSYCL_CLANG="/opt/rocm/llvm/bin/clang"
export HIPSYCL_ROCM_LINK_LINE="-lstdc++ -rpath $HIPSYCL_ROCM_LIB_PATH -L/opt/rocm/lib -lhip_hcc"
```

Re-login or execute the export commands above to apply.

To test, try compile [add_two_vectors.cpp](https://github.com/illuhad/hipSYCL/tree/v0.8.0\#example):
```bash
$ mkdir -p ~/examples/sycl-add_two_vectors
$ cd ~/examples/sycl-add_two_vectors
$ /opt/rocm/hipsycl/bin/syclcc-clang add_two_vectors.cpp -o add_two_vectors
$ ./add_two_vectors
```

The output should be:
```
Result:
0
4
0
8
0
```

**Comment by illuhad** [comment] 2020-02-18 14:45
This is fixed in current hipSYCL master. I also recommend setting the `HIPSYCL_GPU_ARCH`, `HIPSYCL_CLANG`, `HIPSYCL_ROCM_LINK_LINE` etc parameters with cmake (`-DDEFAULT_GPU_ARCH`, `-DROCM_LINK_LINE`, `-DLLVM_DIR`). This will then make hipSYCL use those settings by default without having to modify the environment.

**Comment by nikAizuddin** [comment] 2020-02-18 17:11
@illuhad 
> I also recommend setting the HIPSYCL_GPU_ARCH, HIPSYCL_CLANG, HIPSYCL_ROCM_LINK_LINE etc parameters with cmake (-DDEFAULT_GPU_ARCH, -DROCM_LINK_LINE, -DLLVM_DIR)

Noted, I have updated my comment.
