### ISSUE TITLE
very slow atomic operations over unified memory

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#3177] opened 2023-03-03 22:12 UTC
Running a HIP program that calls hipManagedMalloc() functions is very slow on a MI-series GPU. If the HIP program is not written properly, please let me know. Thanks.
```
make source=main-um.cu
hipcc  -std=c++14 -Wall -I../atomicIntrinsics-cuda -O3 -c main-um.cu -o main-um.o
hipcc  -std=c++14 -Wall -I../atomicIntrinsics-cuda -O3 main-um.o -o main
./main 1
PASS
Average kernel execution time: 130903496.000000 (us)
```
https://github.com/zjin-lcf/HeCBench/blob/master/src/atomicIntrinsics-hip/main-um.cu

**Comment by jatinx** [comment] 2023-03-15 23:21
Thanks for reporting it. Will look into it.

**Comment by ppanchad-amd** [comment] 2024-04-11 14:13
@jatinx Did you have a chance to look into this? Thanks!

**Comment by harkgill-amd** [comment] 2024-07-18 15:51
Hi @zjin-lcf, looks like the file linked is no longer available. 

Could you please provide another example so we can try to reproduce this issue internally?

**Comment by zjin-lcf** [comment] 2024-07-19 15:40
Sorry, the link is updated.

**Comment by b-sumner** [comment] 2024-07-19 16:02
@zjin-lcf that code has every single thread hammering on a small set of locations in very few cache lines.  Code doing that should be expected to be "slow".  However, we are introducing a compiler optimization to recognize uniform addresses and reduce memory traffic.  That will help this code, but won't help the general case where the uniformity can't be deduced.

**Comment by ppanchad-amd** [comment] 2024-09-30 17:29
Hi @zjin-lcf, please let us know if we can go ahead and close this ticket. Thanks!

**Closed as completed** 2024-10-11 17:29 UTC
