### ISSUE TITLE
rocm 5.7: hipcc crashes if ranges is included nd g++-12 is installed

### ISSUE THREAD

**Issue by romintomasetti** [ROCm-Developer-Tools/HIP#3341] opened 2023-09-29 07:41 UTC
This issue is a duplicate of

* ROCm-Developer-Tools/HIPCC/issues/137

that I created yesterday. But it seems this repository gets more activity.

I think this is a critical bug by the way, since it is impossible to compile a decent `c++20` simple code with `hipcc` provided by `ROCm 5.7`.

If this is not the right place for this kind of issue, I'd be glad to create it elsewhere!

Thanks.

**Comment by romintomasetti** [comment] 2023-09-29 07:41
@maartenarnst will be interested in this.

**Comment by cjatin** [comment] 2023-09-29 11:20
Tagging @yxsamliu who can correct me if I am wrong here.

I think this is a clang issue, not a hipcc or hip runtime issue.
clang, in this case shipped with ROCm 5.7 is not compatible with libstdc++ shipped with g++-12.

If you want to use C++20 features, maybe using libc++ shipped with clang (instead of using libstdc++ shipped with gcc/g++) makes sense, at least till this issue is fixed in clang.

I tried building and running it with libc++ and it runs fine.

```shell
➜  build cat t.cc
#include <ranges>

int main() { return 0; }
➜  build hipcc t.cc -std=c++20 -stdlib=libc++ -L ./lib -o ranges
➜  build ./ranges
➜  build
```

**Comment by romintomasetti** [comment] 2023-09-29 12:09
Hi @cjatin ! Actually I updated the issue ROCm-Developer-Tools/HIPCC/issues/137.

In fact, even **without** installing `gcc-12`, it does not work (*i.e.* when it uses the default `gcc` on `Ubuntu 22.04`, that is `gcc-11`). Basically, the `clang` shipped with `hipcc` in `ROCm 5.7` is `clang 17.0.0` and is buggy. If you install `clang++ 17.0.2` from https://apt.llvm.org/ and set `HIP_CLANG_PATH` to point to this newly installed `clang++-17`, it works fine.

Also, though your workaround works for a single file, I think it would not work in our case, because we rely on libraries that have been compiled with the system `gcc` (I expect issues when linking such `gcc`-compiled libraries with some executable compiled with `hipcc` using your workaround with `-stdlib=libc++`).

**Comment by romintomasetti** [comment] 2023-10-02 10:50
Hi @cjatin @yxsamliu !

What's the plan for fixing this? I guess aligning the `clang` version shipped with `hipcc` to the latest available official release of `clang` from `LLVM` could do the trick.

I also have 2 very practical question:
1. When do you plan the next release of `ROCm` that would incorporate the fix?
2. How could we ensure this never happens again? (*e.g.* by adding some test somewhere)

**Comment by yxsamliu** [comment] 2023-10-08 05:01
The issue was caused by https://reviews.llvm.org/D146178. It has been reverted in the trunk but not in ROCm 5.7. I will try reverting it in ROCm 6.0. The author has added lit tests to cover the regressions caused by the patch, which should prevent them from happening again.

**Comment by kjayapra-amd** [comment] 2024-01-25 17:20
Please re-open the issue, if this is still seen on the latest ROCm.
Closing this, since the fix has been identified.

**Closed as completed by kjayapra-amd** 2024-01-25 17:20 UTC
