### ISSUE TITLE
[HIPIFY] HipifyAction.cpp behaviour

### ISSUE THREAD

**Issue by incardon** [ROCm-Developer-Tools/HIP#1408] opened 2019-09-11 12:50 UTC
Hi. I was trying to hipify my coda code and I encauter a SIGABORT.

I am using LLVM 9.0 RC 4

The Abort come from this code section in HipifyAction.cpp

``` C++
// The stream/memory arguments default to zero if omitted.
OS << stringifyZeroDefaultedArg(*SM, config.getArg(2)) << ", ";
OS << stringifyZeroDefaultedArg(*SM, config.getArg(3));
```

Processing a launching kernel like this 

``` C++
cl_offload_gpu<decltype(cl1.toKernel()),decltype(v.toKernel()),decltype(os.toKernel())><<<ite.wthr,ite.thr>>>(cl1.toKernel(),v.toKernel(),os.toKernel());
```

It seems that config.getNumArgs() return 2. Accessing with getArg(3) or (4) produce a SIGABORT

I solved doing this

``` C++
// The stream/memory arguments default to zero if omitted.
if (config.getNumArgs() >= 3)
{OS << stringifyZeroDefaultedArg(*SM, config.getArg(2)) << ", ";}
else
{OS << "0,";}
if (config.getNumArgs() >= 4)
{OS << stringifyZeroDefaultedArg(*SM, config.getArg(3));}
else
{OS << "0";}
```

It would be nice to have a real fix

**Comment by emankov** [comment] 2019-09-11 14:06
It is weird. I'm developing on LLLVM trunk, but I have just checked on previous releases: config's `getNumArgs()` always returns 4, and it suits your fix.  Maybe your SIGABORT has occurred due to another problem?

Could you provide your log and source code with the above kernel? I'll try to repro it.

Thanks.

**Comment by incardon** [comment] 2019-09-11 14:52
Refer to issue  #1409

**Comment by emankov** [comment] 2019-11-04 09:53
Not a bug, won't fix.

**Closed by emankov** 2019-11-04 09:53 UTC
Labels: hipify
