### ISSUE TITLE
hipcc aggregate initialization: failure

### ISSUE THREAD

**Issue by nodwellmtt** [ROCm-Developer-Tools/HIP#502] opened 2018-06-07 22:55 UTC
For certain C++ aggregates, under certain conditions hipcc will generate a compiler error if list initialization is used.

Here is an example:

```C++
#include <hip/hip_runtime.h>

/** Simple C++11 aggregate */
template <typename T, size_t N>
struct custom_array
{
    T data[N];

    /** Returns element i. const version */
    __host__ __device__ const T& operator[](size_t i) const {
        return this->data[i];
    }

    /** Returns element i. non-const version */
    __host__ __device__ T& operator[](size_t i) {
        return this->data[i];
    }
};

void a_function()
{
   // This statement is itself OK, but if you comment it out, the statement in main compiles without issue.
    custom_array<float,3> a;
}

int main()
{
    // The compiler error occurs here.
    custom_array<float,3> b = {1.0f, 2.0f, 3.0f};
}
```

The compiler error occurs on the statement in main. Somewhat oddly, if you comment out the line in `a_function`, then `main` compiles without error. The error also does not occur if `__host__ __device__` is removed, but then the object can not be used in device code.

Here is the error:

```
$ hipcc --std=c++11 -I/opt/rocm/include -o verysimple verysimple.cpp 
verysimple.cpp:29:27: error: no matching constructor for initialization of
      'custom_array<float, 3>'
    custom_array<float,3> b = {1.0f, 2.0f, 3.0f};
                          ^   ~~~~~~~~~~~~~~~~~~
verysimple.cpp:5:8: note: candidate constructor (the implicit copy constructor)
      not viable: requires 1 argument, but 3 were provided
struct custom_array
       ^
verysimple.cpp:5:8: note: candidate constructor (the implicit move constructor)
      not viable: requires 1 argument, but 3 were provided
verysimple.cpp:5:8: note: candidate constructor (the implicit default
      constructor) not viable: requires 0 arguments, but 3 were provided
1 error generated.
```

**Comment by nodwellmtt** [comment] 2018-06-07 22:56
HIP version information:

```
$ hipcc --version
HIP version: 1.5.18151
HCC clang version 7.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang 86791fc4961dc8ffde77bde20d7dfa5e5cbeff5e) (ssh://gerritgit/compute/ec/hcc-tot/llvm 0ccef158132e1222d549edf2da33d4bc0be6c2d1) (based on HCC 1.2.18175-6e93604-86791fc-0ccef15 )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
```

**Comment by nodwellmtt** [comment] 2018-06-12 21:00
Here is another example, slightly different:
  - List initialization is used only on the standard C++ library object std::array.
  - The compiler error is triggered by defining and instantiating a class with a device method that takes std::array as an argument. (Yes, this works in device code).
  - Exactly the same statement does not cause a compiler error after the above class is instantiated, but it does afterwards. Note that the compiler error actually has nothing to do with the class that has the method in question: that class only has to exist to cause the error.

```C++
#include <hip/hip_runtime.h>
#include <array>

/** A skeleton for a multi-dimensional dynamically allocated array. */
template <typename T, size_t N>
class multi_array
{
private:
    std::array<size_t,N> m_dims;  // dimensions of array
    T* m_data;                    // actual data

public:
    multi_array(std::array<size_t,N> dims) {
        // Allocate here on the device...
    }

    /** Returns element with multi-dimensional indices.
      * Note that this is a __device__function, because it is to be called
      * in device code to access the data allocated on the device.
      */
    __device__ T operator()(std::array<size_t,N> indices) const {
        // For demonstration just return 0: in reality would return the actual
        // value of specified element.
        return 0;
    }
};

int main() {
    // This statement compiles OK
    std::array<size_t,3> dims = {100,200,64};

    multi_array<float,3> M(dims);

    // This effectively identical statement causes now a compiler error,
    // only because it is after the instantiation of multi_array.
    std::array<size_t,3> dims2 = {100,200,64};
}
```

Here is the compiler output:

```
$ hipcc -std=c++11 -I/opt/rocm/include -o demo3 demo3.cpp
demo3.cpp:36:26: error: no matching constructor for initialization of
      'std::array<size_t, 3>' (aka 'array<unsigned long, 3>')
    std::array<size_t,3> dims2 = {100,200,64};
                         ^       ~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/array:89:12: note: 
      candidate constructor (the implicit copy constructor) not viable:
      requires 1 argument, but 3 were provided
    struct array
           ^
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/array:89:12: note: 
      candidate constructor (the implicit move constructor) not viable:
      requires 1 argument, but 3 were provided
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/array:89:12: note: 
      candidate constructor (the implicit default constructor) not viable:
      requires 0 arguments, but 3 were provided
1 error generated.
```

**Comment by SarbojitAMD** [comment] 2019-10-28 03:32
@nodwellmtt, 
It is hcc compiler issue that will soon get deprecated as HIP is transitioning to the Clang compiler. I have verified that the issue is not seen on the Clang compiler. Steps are mentioned https://github.com/ROCm-Developer-Tools/HIP/blob/master/INSTALL.md#hip-clang you may want to take a look.

I am closing the bug as 'will not fix' as it is working fine with Clang compiler.

Feel free to respond in case you need any further help.

**Closed by SarbojitAMD** 2019-10-28 03:32 UTC
Labels: hcc
