### ISSUE TITLE
ROCm 2.0 clock64 function not working properly

### ISSUE THREAD

**Issue by marialubeznov** [ROCm-Developer-Tools/HIP#978] opened 2019-03-20 18:47 UTC
Hi!
I am trying to implement a sleep function as GPU kernel. It worked fine in CUDA, but in HIP the kernel launch hangs infinitely **unless** I add a printf inside the kernel.  

Thanks
Maria

This is the code:
```
#define HIP_ENABLE_PRINTF
#define HCC_ENABLE_PRINTF

#include <iostream>
#include <hip/hip_runtime.h>
#include <time.h>

const int num_streams = 2;

__device__ void sleep(long long sleep_cycles)
{
    long long start = clock64();
    long long cycles_elapsed;
    do { 
        cycles_elapsed = clock64() - start; 
        //printf("cycles_elapsed = %d sleep_cycles = %d \n", cycles_elapsed, sleep_cycles);
    } while (cycles_elapsed < sleep_cycles);
}

__global__ void SleepTask(long long sleep_cycles) {
    sleep(sleep_cycles);   
}

int main() {
    hipDeviceProp_t devProp;
    hipGetDeviceProperties(&devProp, 0);

    std::cout << "Device name " << devProp.name << std::endl;

    hipSetDevice(0);

    hipStream_t streams[num_streams];

    for (int i = 0; i < num_streams; i++) hipStreamCreate(&streams[i]);
    printf("Launching kernel \n");
    long long short_sleep = 100;
    hipLaunchKernelGGL(SleepTask, dim3(64, 1, 1), dim3(1, 1, 1), 0, 0, short_sleep);
    hipDeviceSynchronize();
    hipDeviceReset();
    return 0;
}
```

**Comment by iotamudelta** [comment] 2019-03-20 19:16
@marialubeznov this is a known issue with ROCm 2.2 related to `clock64()`, unfortunately. The fix is scheduled for the next release.

**Comment by gargrahul** [comment] 2019-04-18 18:40
@marialubeznov I am closing this issue. Please reopen this if the issue is not resolved in ROCm2.3.

**Closed by gargrahul** 2019-04-18 18:40 UTC
