### ISSUE TITLE
must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__

### ISSUE THREAD

**Issue by merlinzone** [ROCm-Developer-Tools/HIP#143] opened 2017-08-05 05:13 UTC
I try to hipify a cuda project to hip.
Ubuntu 16.04.2, rocm 1.6, amd r9 nano card.
/opt/rocm/hip/include/hip/hip_runtime.h:59:2: error: #error ("Must define exactly one of _ _ HIP_PLATFORM_HCC _ _ or _ _ HIP_PLATFORM_NVCC _ _");
 #error("Must define exactly one of  _ _ HIP_PLATFORM_HCC _ _ or _ _ HIP_PLATFORM_NVCC _ _");

found in hip_common.h
#if defined(_ _ HCC _ _)
#define  _ _ HIP_PLATFORM_HCC _ _
#endif //_ _ HCC _ _

how to define _ _ HIP_PLATFORM_HCC _ _ or _ _ HCC _ _  in Makefile or environment?

**Comment by MikalaiDrabovich** [comment] 2017-08-05 06:47
This may be helpful: https://github.com/ROCm-Developer-Tools/HIP/pull/144/commits/a0b33b803ea609b5d428b515bcfadd0ff845f4bc

**Comment by merlinzone** [comment] 2017-08-05 08:13
not work.
I try to define it in Makefile "-D __HIP_PLATFORM_HCC__" like that
https://github.com/briansp2020/Parboil/blob/hip_bfs/benchmarks/bfs/src/hip_base/Makefile
or "-D__HCC"

**Comment by mangupta** [comment] 2017-08-08 10:41
@merlinzone: Can you confirm if you are using hipcc for compiling the code? If detected target platform is  hcc, we define ```-D__HCC__``` here in [hipcc](https://github.com/ROCm-Developer-Tools/HIP/blob/master/bin/hipcc#L100). This in turn automatically defines ```__HIP_PLATFORM_HCC__``` in ```hip_common.h```. When using nvcc for compiling HIP code, we make use of nvcc auto-defining ```__NVCC__``` to automatically define ```__HIP_PLATFORM_NVCC__``` in ```hip_common.h```.

If you are using a compiler other than hipcc please refer to the [using a standard c compiler](https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_porting_guide.md#using-a-standard-c-compiler) section in the HIP porting guide.

**Comment by merlinzone** [comment] 2017-08-11 07:38
I can confirm I use hipcc for compiling the code.
I tried:
`-D__HCC__`
` -D__HIP_PLATFORM_HCC__ `
`export HIP_PLATFORM=hcc`
`export PLATFORM=hcc`
but does not work.

**Comment by mangupta** [comment] 2017-08-11 09:26
As I mentioned, if you are using hipcc, you don't need to explicitly define ```-D__HCC__``` or ```-D__HIP_PLATFORM_HCC__```. Both should get done automatically.

Is it possible to share the entire output of your build command? Please set ```export HIPCC_VERBOSE=7``` before you run your build command.

**Comment by mangupta** [comment] 2017-08-23 10:42
@merlinzone Could please share the above requested data?

**Comment by mangupta** [comment] 2017-12-05 05:24
Been waiting for the data for over 3 months. Closing the issue assuming the issue is no longer observed or is resolved. If not, please reopen the ticket and provide the requested data.

**Closed by mangupta** 2017-12-05 05:24 UTC
