### ISSUE TITLE
The attribute hipFuncAttributeMaxDynamicSharedMemorySize is ignored 

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#3122] opened 2022-12-26 23:09 UTC
For the attribute `hipFuncAttributeMaxDynamicSharedMemorySize`, the hipFuncSetAttribute may return an error when the memory size exceeds maximum dynamic shared memory size. 

Reference
hipDynamicShared2.cpp

**Comment by abhimeda** [comment] 2024-02-08 15:37
@zjin-lcf Hi, is your issue resolved on the latest HIP? If so can we close this ticket?

**Comment by zjin-lcf** [comment] 2024-02-08 17:37
No. Thanks.

**Comment by ppanchad-amd** [comment] 2024-04-10 18:24
@zjin-lcf Internal ticket has been created to resolve this issue. Thanks!

**Comment by akondrat-amd** [comment] 2024-04-19 01:29
@zjin-lcf Can you provide more details of your setup and steps to reproduce?

**Comment by zjin-lcf** [comment] 2024-04-19 13:08
The file /tests/src/kernel/hipDynamicShared2.cpp shows the usage of the function.

The hipFuncSetAttribute may return an error when the memory size (SIZE) exceeds maximum dynamic shared memory size.

```
hipError_t ret = hipFuncSetAttribute(
        reinterpret_cast<const void*>(&vectorAdd),
        hipFuncAttributeMaxDynamicSharedMemorySize, SIZE);
```

**Comment by taylding-amd** [comment] 2024-10-09 19:05
Hi @zjin-lcf,

Thank you for raising your concerns. You are correct that if the maximum size of dynamic shared memory that the kernel can allocate exceeds the maximum dynamic shared memory size allowed by the system, the ```hipFuncSetAttribute``` function may return an error. This occurs because it is not safe to assign an attribute value larger than what the system permits.

We handle the error as follows:
```
if (ret != hipSuccess) {
    printf("Failed requesting enough shared memory size (%zu), error: '%s' (%d), ignored!\n",
           SIZE, hipGetErrorString(ret), ret);
    passed();
}
```
After attempting to set the attribute, if it is not successful, it indicates that there was an error in setting the attribute. In the event of an error, the code prints a message to the console using ```printf```.

If you have any further concerns, please let us know your use case when the error occurred, including details about your environment and the relevant code.

**Comment by taylding-amd** [comment] 2024-10-22 14:05
Hi, this issue will be closed now due to inactivity. Please feel free to reopen it or ask follow-up questions should further assistance be required. Thanks!

**Closed as completed by taylding-amd** 2024-10-22 14:05 UTC
Labels: Under Investigation
