### ISSUE TITLE
Program compiled with `hipcc -O0` from ROCm 5.3.2 do not run correctly

### ISSUE THREAD

**Issue by fxzjshm** [ROCm-Developer-Tools/HIP#3090] opened 2022-11-17 17:56 UTC
Using [vectoradd_hip.cpp](https://github.com/ROCm-Developer-Tools/HIP-Examples/blob/master/vectorAdd/vectoradd_hip.cpp) from HIP examples, the executable produced by hipcc from ROCm 5.3.2 with `-O0` flag cannot run correctly.

Log:
```
➜  test /opt/rocm-5.2.3/bin/hipcc -O0 vectoradd_hip.cpp -o vectoradd_hip_O0_5.2.3
➜  test /opt/rocm-5.2.3/bin/hipcc -O1 vectoradd_hip.cpp -o vectoradd_hip_O1_5.2.3
➜  test /opt/rocm-5.3.2/bin/hipcc -O0 vectoradd_hip.cpp -o vectoradd_hip_O0_5.3.2
➜  test /opt/rocm-5.3.2/bin/hipcc -O1 vectoradd_hip.cpp -o vectoradd_hip_O1_5.3.2
➜  test ./vectoradd_hip_O0_5.2.3
 System minor 0
 System major 9
 agent prop name AMD Radeon VII
hip Device prop succeeded 
PASSED!                                                                    /0.4s
➜  test ./vectoradd_hip_O1_5.2.3
 System minor 0
 System major 9
 agent prop name AMD Radeon VII
hip Device prop succeeded 
PASSED!                                                                    /0.4s
➜  test ./vectoradd_hip_O0_5.3.2
 System minor 0
 System major 9
 agent prop name AMD Radeon VII
hip Device prop succeeded 
FAILED: 1048576 errors                                                     /0.5s
➜  test ./vectoradd_hip_O1_5.3.2
 System minor 0
 System major 9
 agent prop name AMD Radeon VII
hip Device prop succeeded 
PASSED!                                                                    /0.5s
```

Seems a clang-15 + ROCm 5.3.2 problem.

Related discussion: illuhad/hipSYCL#869

**Comment by zjin-lcf** [comment] 2022-12-06 23:39
I could reproduce the error with ROCm 5.4 on a MI-series GPU.

**Comment by abhimeda** [comment] 2024-02-08 15:34
@fxzjshm Hi, is your issue resolved on the latest HIP? If so can we close this ticket?

**Comment by fxzjshm** [comment] 2024-02-08 16:09
Not reproduced with ROCm 5.7.0 + gfx1100 & ROCm 6.0.0 + gfx1035, will test gfx906 once have access again.

**Comment by fxzjshm** [comment] 2024-02-22 12:37
Still reproduced with ROCm 6.0.0 & 6.0.2 + gfx906.

**Comment by ppanchad-amd** [comment] 2024-04-10 18:00
@fxzjshm Internal ticket has been created to resolve this issue. Thanks!

**Comment by nartmada** [comment] 2024-05-01 03:46
@fxzjshm, which GPU are you currently to repro the issue?  MI50, Radeon PRO VII, or Radeon VII?  Thanks.

**Comment by fxzjshm** [comment] 2024-05-01 15:35
@nartmada It's Radeon VII, as shown above in the log. Is this bug reproducible on your test environment?

**Comment by harkgill-amd** [comment] 2024-07-19 18:35
Hi @fxzjshm, I was unable to reproduce your issue compiling the vectoradd_hip.cpp program with the `-O0` flag on gfx906. Please see the output below.

```
rocm@rocm:~/vecadd$ hipcc -O0 vectoradd_hip.cpp -o vectoradd
#Warnings
rocm@rocm:~/vecadd$ ./vectoradd
 System minor 0
 System major 9
 agent prop name AMD Radeon VII
hip Device prop succeeded
PASSED!
```
This was tested on the latest ROCm 6.1.2 release. I will close this ticket for now, if you encounter this issue again, feel free to re-open this issue. Thanks!

**Closed as completed by harkgill-amd** 2024-07-19 18:35 UTC
Labels: Under Investigation
