### ISSUE TITLE
Add support for cudaOccupancyMaxActiveBlocksPerMultiprocessor

### ISSUE THREAD

**Issue by Jorghi12** [ROCm-Developer-Tools/HIP#439] opened 2018-05-08 17:55 UTC
This is a pretty important instruction when designing kernels that are highly performant for the selected GPU architecture.

**Comment by emankov** [comment] 2018-05-08 18:00
Hah, it's only implemented in fallback nvcc path.

**Comment by Jorghi12** [comment] 2018-05-08 18:04
Can we have it implemented for hcc path :)

**Comment by mangupta** [comment] 2018-07-19 02:24
Marking this as a duplicate of the newer #567 which is the same request.

**Closed by mangupta** 2018-07-19 02:24 UTC
Labels: hip, type:feature
