### ISSUE TITLE
[HIPIFY] File extension '.C' recognition

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#1649] opened 2019-11-09 14:05 UTC
It seems that the file extension '.C' is not recognized by the hip toolchain to examine the CUDA APIs.

**Comment by emankov** [comment] 2019-11-09 15:01
Do you mean `hipify-clang -examine` or what?

**Comment by zjin-lcf** [comment] 2019-11-09 15:15
I tried hipexamine-perf.sh

**Comment by emankov** [comment] 2019-11-09 17:26
Both `hipexamine-perl` and `hipexamine` supports `*.c` extension. Could you please be more concrete: provide your usecase.

**Comment by emankov** [comment] 2019-11-20 06:30
Ping

**Comment by emankov** [comment] 2019-12-27 13:44
Closing it as "not a bug" after double-checking.

**Closed by emankov** 2019-12-27 13:44 UTC
Labels: hipify
