### ISSUE TITLE
Low bandwidth for a data conversion program in HIP on an AMD GPU

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#3043] opened 2022-10-31 11:19 UTC
Running a SYCL program on an NVIDIA GPU and an AMD GPU shows that the bandwidth is significantly low on an AMD GPU. Hence, the issue was initially posted (https://github.com/intel/llvm/issues/7195). 

After converting the program from SYCL to HIP (https://github.com/zjin-lcf/HeCBench/tree/master/src/conversion-hip), I find that the bandwidth of the HIP program seems similar to that of the SYCL program. If the HIP program using hipMallocManaged() is not written properly, please let me know. Thanks.

**Comment by abhimeda** [comment] 2024-02-07 19:08
@zjin-lcf  Hi, were you able to resolve this issue on the latest HIP? If so can we close this ticket?

**Comment by zjin-lcf** [comment] 2024-02-07 19:19
No. Thanks.

**Comment by abhimeda** [comment] 2024-02-08 16:11
@zjin-lcf An internal ticket has been opened to help resolve this issue. Could we have your OS, GPU, CPU versions?

**Comment by zjin-lcf** [comment] 2024-02-08 17:31
Ubuntu 22.04, MI100, AMD EPYC 7272 processor

**Comment by mangupta** [comment] 2024-05-31 14:00
@zjin-lcf : The HIP reproducer mentioned in your initial post is no longer available. Can you please link to a simple HIP reproducer so that we can understand the issue.

**Comment by zjin-lcf** [comment] 2024-05-31 17:49
Sorry. The link is updated.

**Comment by mangupta** [comment] 2024-06-05 05:26
@zjin-lcf : Thanks for the updated link. I see that you are using hipMallocManaged without using any prefetch hints in your example. Can you share the output of ```rocminfo | grep amdgcn```?
Also can you please set the environment variable AMD_LOG_LEVEL=4, rerun the reproducer and share the generated output trace?
In the reproducer, I see that you the source and destination buffers are allocated using hipMallocManaged, but not populated using any data. Probably because this is a synthetic test. In that case, can you see what happens if you replace hipMallocManaged with hipMalloc instead?

**Comment by jinz2014** [comment] 2024-06-05 15:02
amdgcn-amd-amdhsa--gfx908:sramecc+:xnack-

After the replacement, I observe significant BW increase.  

I replaced MallocManaged with Malloc in the GPU programs in the repository. I think the programs are supposed to measure the conversion time only.

It seems that the impact of cudaMallocManaged on the execution time of the CUDA program is small. Thanks for your comments/suggestions.

**Comment by zjin-lcf** [comment] 2024-06-05 15:05
amdgcn-amd-amdhsa--gfx908:sramecc+:xnack-

After the replacement, I observe significant BW increase.

I replaced MallocManaged with Malloc in the GPU programs in the repository. I think the programs are supposed to measure the conversion time only.

It seems that the impact of cudaMallocManaged on the execution time of the CUDA program is small. Thanks for your comments/suggestions.

**Comment by mangupta** [comment] 2024-06-05 15:40
@zjin-lcf : "amdgcn-amd-amdhsa--gfx908:sramecc+:xnack-" does not support managed memory. HIP runtime will fallback to allocating system memory that is made visible to all devices instead to keep the code functional. That is why you are seeing reduced performance and see better performance when using hipMalloc instead.

**Comment by zjin-lcf** [comment] 2024-06-05 17:48
Ok. Is there a link that explains the difference between managed memory and system memory ?

**Comment by mangupta** [comment] 2024-06-06 04:16
system memory = host memory. It is the same as memory allocated using hipHostMalloc.

**Closed as completed** 2024-06-06 13:57 UTC
Labels: Under Investigation
